from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import Column, Integer, String, Float, DateTime

from flask import Flask
app = Flask(__name__)
app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///project.db"
db = SQLAlchemy(app)

class Players(db.Model):
    __tablename__ = 'players'
    realgm_id = Column('RealGM ID', Integer, primary_key=True, nullable=False)
    season = Column('Season', String(6), quote=True)
    name = Column('Name', String, quote=True)
    position_1 = Column('Position 1', String(2), quote=True)
    position_2 = Column('Position 2', String(2), quote=True)
    play_style = Column('Play Style', String, quote=True)
    height = Column('Height', Integer, quote=True)
    weight = Column('Weight', Float, quote=True)
    school = Column('School', String, quote=True)
    conference = Column('Conference', String, quote=True)
    wins = Column('Wins', Integer, quote=True)
    losses = Column('Losses', Integer, quote=True)
    sos = Column('SOS', Float, quote=True)
    class_year = Column('Class', Integer, quote=True)
    birthday = Column(String)
    draft_day_age = Column('Draft Day Age', Float, quote=True)
    rsci = Column('RSCI', Integer, quote=True)
    g = Column('G', Integer, quote=True)
    gs = Column('GS', Integer, quote=True)
    mp = Column('MP', Integer, quote=True)
    per = Column('PER', Float, quote=True)
    ts_pct = Column('TS%', Float, quote=True)
    efg_pct = Column('eFG%', Float, quote=True)
    three_par = Column('3PAr', Float, quote=True)
    ftr = Column('FTr', Float, quote=True)
    pprod = Column('PProd', Integer, quote=True)
    orb_pct = Column('ORB%', Float, quote=True)
    drb_pct = Column('DRB%', Float, quote=True)
    trb_pct = Column('TRB%', Float, quote=True)
    ast_pct = Column('AST%', Float, quote=True)
    stl_pct = Column('STL%', Float, quote=True)
    blk_pct = Column('BLK%', Float, quote=True)
    # stock_pct = Column(Float)
    # tov_pct = Column(Float)
    # adjusted_tov_pct = Column(Float)
    usg_pct = Column('USG%', Float, quote=True)
    # offensive_load = Column(Float)
    # ows = Column(Float)
    # dws = Column(Float)
    # ws = Column(Float)
    ws_per40 = Column('WS/40', Float, quote=True)
    # obpm = Column(Float)
    # dbpm = Column(Float)
    bpm = Column('BPM', Float, quote=True)
    ast_tov = Column('AST/TOV', Float, quote=True)
    off_rtg = Column('OFF RTG', Float, quote=True)
    def_rtg = Column('DEF RTG', Float, quote=True)
    # hands_on_buckets = Column(Float)
    # pure_point_rating = Column(Float)
    # fg_per40 = Column(Float)
    # fga_per40 = Column(Float)
    # fg_pct = Column(Float)
    # two_fg_per40 = Column(Float)
    # two_fga_per40 = Column(Float)
    # two_fg_pct = Column(Float)
    # three_fg_per40 = Column(Float)
    # three_fga_per40 = Column(Float)
    three_fg_pct = Column('3FG%', Float, quote=True)
    # three_point_proficiency = Column(Float)
    # three_point_confidence = Column(Float)
    # ft_per40 = Column(Float)
    # fta_per40 = Column(Float)
    ft_pct = Column('FT%', Float, quote=True)
    # trb_per40 = Column(Float)
    # ast_per40 = Column(Float)
    # stl_per40 = Column(Float)
    # blk_per40 = Column(Float)
    # tov_per40 = Column(Float)
    # pf_per40 = Column(Float)
    # pts_per40 = Column(Float)
    # fg_per100poss = Column(Float)
    # fga_per100poss = Column(Float)
    # two_fg_per100poss = Column(Float)
    # two_fga_per100poss = Column(Float)
    # three_fg_per100poss = Column(Float)
    # three_fga_per100poss = Column(Float)
    # three_point_proficiency = Column(Float)
    # three_point_confidence = Column(Float)
    # ft_per100poss = Column(Float)
    # fta_per100poss = Column(Float)
    # trb_per100poss = Column(Float)
    # ast_per100poss = Column(Float)
    # stl_per100poss = Column(Float)
    # blk_per100poss = Column(Float)
    # tov_per100poss = Column(Float)
    # pf_per100poss = Column(Float)
    # pts_per100poss = Column(Float)
    # num_dunks = Column(Integer)
    # dunks_vs_rim_shot_pct = Column(Float)
    # pct_dunks_unassisted = Column(Float)
    # dunks_per_minute_played = Column(Float)
    # unassisted_shots_at_rim_per100poss = Column(Float)
    # pct_shots_at_rim = Column(Float)
    fg_pct_at_rim = Column('FG% @ Rim', Float, quote=True)
    # pct_assisted_at_rim = Column(Float)
    # pct_shots_at_mid = Column(Float)
    # fg_pct_at_mid = Column(Float)
    # pct_assisted_at_mid = Column(Float)
    # pct_shots_at_three = Column(Float)
    # pct_assisted_at_three = Column(Float)
    # pct_assisted = Column(Float)
    # aau_season = Column(String)
    # aau_team = Column(String)
    # aau_league = Column(String)
    # aau_gp = Column(Integer)
    # aau_gs = Column(Integer)
    # aau_min = Column(Float)
    # aau_pts = Column(Float)
    # aau_fgm = Column(Float)
    # aau_fga = Column(Float)
    # aau_fg_pct = Column(Float)
    # aau_3pm = Column(Float)
    # aau_3pa = Column(Float)
    # aau_3p_pct = Column(Float)
    # aau_ftm = Column(Float)
    # aau_fta = Column(Float)
    # aau_ft_pct = Column(Float)
    # aau_orb = Column(Float)
    # aau_drb = Column(Float)
    # aau_trb = Column(Float)
    # aau_ast = Column(Float)
    # aau_stl = Column(Float)
    # aau_blk = Column(Float)
    # aau_tov = Column(Float)
    # aau_pf = Column(Float)
    # event_year = Column(String)
    # event_name = Column(String)
    # event_gp = Column(Integer)
    # event_min = Column(Float)
    # event_pts = Column(Float)
    # event_fgm = Column(Float)
    # event_fga = Column(Float)
    # event_fg_pct = Column(Float)
    # event_3pm = Column(Float)
    # event_3pa = Column(Float)
    # event_3p_pct = Column(Float)
    # event_ftm = Column(Float)
    # event_fta = Column(Float)
    # event_ft_pct = Column(Float)
    # event_trb = Column(Float)
    # event_ast = Column(Float)
    # event_stl = Column(Float)
    # event_blk = Column(Float)
    # event_tov = Column(Float)
    # event_pf = Column(Float)
    # event_placement = Column(String(10))
    finishing_score = Column('Finishing Score', Float, quote=True)
    shooting_score = Column('Shooting Score', Float, quote=True)
    shot_creation_score = Column('Shot Creation Score', Float, quote=True)
    passing_score = Column('Passing Score', Float, quote=True)
    rebounding_score = Column('Rebounding Score', Float, quote=True)
    athleticism_score = Column('Athleticism Score', Float, quote=True)
    defense_score = Column('Defense Score', Float, quote=True)
    college_productivity_score = Column('College Productivity Score', Float, quote=True)
    percentile_score = Column('Percentile Score', Float, quote=True)
    box_score_creation = Column('Box Score Creation', Float, quote=True)
    rim_shot_creation = Column('Rim Shot Creation', Float, quote=True)
    helio_score = Column('Helio Score', Float, quote=True)
    draft_score = Column('Draft Score', Float, quote=True)
    image_link = Column('Image Link', String, quote=True)
    
class Picks(db.Model):
    __tablename__ = 'picks'
    id = Column(Integer(), primary_key=True, nullable=False)
    date = Column(DateTime())
    ip = Column(String(20))
    user_agent = Column(String(255))
    win_player_id = Column(Integer())
    win_player_name = Column(String(60))
    lose_player_id = Column(Integer())
    lose_player_name = Column(String(60))
    
with app.app_context():
    db.create_all()